name: model_concepts
version: 1.0.2

description: A graphical model designer for dartling.
homepage: https://github.com/dzenanr/model_concepts
documentation: http://goo.gl/Fd08zZ
environment:
  sdk: '>=2.18.6 <3.0.0'

